<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Authors>Noviyanto Wibowo</Authors>
    <RootNamespace>LinqToDb.Repository</RootNamespace>
    <RepositoryUrl>https://github.com/opxw/linq2db-repository</RepositoryUrl>
    <Version>1.0.9</Version>
    <Description>Generic repository pattern using linq2db</Description>
    <PackageIcon>logo.png</PackageIcon>
    <PackageReadmeFile>docs.md</PackageReadmeFile>
    <Title>Generic Repository LinqToDb</Title>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net9.0|AnyCPU'">
    <DebugType>none</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net10.0|AnyCPU'">
    <DebugType>none</DebugType>
  </PropertyGroup>

	<ItemGroup>
    <None Include="..\docs.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\logo.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

	<ItemGroup>
	  <PackageReference Include="linq2db" Version="6.2.1" />
	  <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.5" />
	</ItemGroup>

</Project>
